version: "3.8"
name: gabom

services:
  redis:
    image: redis:7-alpine
    container_name: redis
#    ports:
#      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # 관리 UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-admin}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    image: gabom-server:${TAG:-dev}
    container_name: gabom-container
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # application-dev.yml 기본값과 매칭 (필요시 .env로 오버라이드)
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-admin}
      REDIS_HOST: redis
      REDIS_PORT: 6379

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_REDIS_HOST: redis

    ports:
      - "${SERVER_PORT:-8080}:8080"
    restart: always
    volumes:
      - ./logs:/logs

volumes:
  redis_data:
  rabbitmq_data: