server:
  port: 8080
  error:
    include-stacktrace: always

logging:
  level:
    com.explorer.gabom: debug

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gabom?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "localsecretkeylocalsecretkeylocalsecretkeylocalsecretkey"
  access-expiration: 3600000  # 1시간
  refresh-expiration: 1209600000  # 14일