server:
  port: 8080
  error:
    include-stacktrace: always

logging:
  level:
    com.explorer.gabom: debug

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gabom?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  # 이메일 인증 시 필요
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "localsecretkeylocalsecretkeylocalsecretkeylocalsecretkey"
  access-expiration: 3600000  # 1시간
  refresh-expiration: 1209600000  # 14일