server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: always

logging:
  level:
    com.explorer.gabom: debug

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_URL}:${DEV_MYSQL_PORT}/${DEV_MYSQL_DBNAME}?serverTimezone=Asia/Seoul
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  # 이메일 인증 시 필요
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

# AWS 설정
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_BUCKET_REGION}
      s3:
        bucket: ${AWS_BUCKET_NAME}
        key:
          prefix: test/

  # redis 설정
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

# jwt 설정
jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: 3600000  # 1시간
  refresh-expiration: 1209600000  # 14일

# Swagger 설정
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    enabled: true               # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8080/swagger-ui/index.html>
    tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha